version: '3'
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: petsys
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app_network
    app:
        build: .
        depends_on:
            - postgres
        ports:
            - '3000:3000'
            - '8080:8080'
        volumes:
            - .:/app
        networks:
            - app_network
volumes:
    pgdata:
networks:
    app_network:
